In [1]:
import pandas as pd
import numpy as np
import glob

In [2]:
# list all csv files only
csv_files = glob.glob('Resources/JC-*.csv')
csv_files

['Resources/JC-202209-citibike-tripdata.csv',
 'Resources/JC-202207-citbike-tripdata.csv',
 'Resources/JC-202205-citibike-tripdata.csv',
 'Resources/JC-202208-citibike-tripdata.csv',
 'Resources/JC-202206-citibike-tripdata.csv']

In [3]:
combined_citibike_csv = pd.concat([pd.read_csv(file) for file in csv_files ], ignore_index=True)
combined_citibike_csv

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,4999883C92EACCB0,classic_bike,2022-09-01 21:05:47,2022-09-01 21:08:07,Jersey & 3rd,JC074,Brunswick St,JC023,40.723332,-74.045953,40.724176,-74.050656,member
1,CC87E6815E075F6F,classic_bike,2022-09-10 18:09:26,2022-09-10 18:11:48,Jersey & 3rd,JC074,Brunswick St,JC023,40.723225,-74.045679,40.724176,-74.050656,member
2,B54E7FDDF4C251E6,classic_bike,2022-09-26 21:46:24,2022-09-26 21:56:06,Jersey & 3rd,JC074,Jersey & 3rd,JC074,40.723275,-74.045694,40.723332,-74.045953,member
3,A19A3DC77A98F6C2,classic_bike,2022-09-08 20:11:41,2022-09-08 22:01:29,Jersey & 3rd,JC074,Jersey & 3rd,JC074,40.723230,-74.045731,40.723332,-74.045953,member
4,3530E340A0B0E93F,classic_bike,2022-09-08 17:05:38,2022-09-08 17:10:26,Leonard Gordon Park,JC080,Riverview Park,JC057,40.745789,-74.057112,40.744319,-74.043991,member
...,...,...,...,...,...,...,...,...,...,...,...,...,...
511756,25AD34565A260732,classic_bike,2022-06-17 16:03:36,2022-06-17 16:33:48,South Waterfront Walkway - Sinatra Dr & 1 St,HB103,11 St & Washington St,HB502,40.736982,-74.027781,40.749985,-74.027150,casual
511757,8A4181FCE9439036,classic_bike,2022-06-25 14:14:26,2022-06-25 14:19:40,South Waterfront Walkway - Sinatra Dr & 1 St,HB103,8 St & Washington St,HB603,40.736982,-74.027781,40.745984,-74.028199,member
511758,28C8501BCB596743,electric_bike,2022-06-04 08:57:04,2022-06-04 09:15:33,Jersey & 6th St,JC027,11 St & Washington St,HB502,40.725289,-74.045572,40.749985,-74.027150,casual
511759,D28575BBFF3A0B57,classic_bike,2022-06-17 06:11:05,2022-06-17 06:21:37,South Waterfront Walkway - Sinatra Dr & 1 St,HB103,11 St & Washington St,HB502,40.736982,-74.027781,40.749985,-74.027150,member
511760,A914FEF9390C201C,electric_bike,2022-06-02 18:15:17,2022-06-02 18:20:22,South Waterfront Walkway - Sinatra Dr & 1 St,HB103,11 St & Washington St,HB502,40.736982,-74.027781,40.749985,-74.027150,member

In [4]:
combined_citibike_csv.dtypes

ride_id                object
rideable_type          object
started_at             object
ended_at               object
start_station_name     object
start_station_id       object
end_station_name       object
end_station_id         object
start_lat             float64
start_lng             float64
end_lat               float64
end_lng               float64
member_casual          object
dtype: object

In [5]:
combined_citibike_csv["started_at"] = pd.to_datetime(combined_citibike_csv["started_at"])
combined_citibike_csv["ended_at"] = pd.to_datetime(combined_citibike_csv["ended_at"])

combined_citibike_csv.dtypes

ride_id                       object
rideable_type                 object
started_at            datetime64[ns]
ended_at              datetime64[ns]
start_station_name            object
start_station_id              object
end_station_name              object
end_station_id                object
start_lat                    float64
start_lng                    float64
end_lat                      float64
end_lng                      float64
member_casual                 object
dtype: object

In [6]:
combined_citibike_csv = combined_citibike_csv.sort_values("started_at")

combined_citibike_csv.head()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
267840,E0888D1157FDBE22,classic_bike,2022-05-01 00:01:29,2022-05-01 00:06:52,Columbus Dr at Exchange Pl,JC106,Morris Canal,JC072,40.716870,-74.032810,40.712419,-74.038526,member
224784,BC0481A24404E4A6,electric_bike,2022-05-01 00:03:39,2022-05-01 00:18:45,JC Medical Center,JC011,Washington St,JC098,40.716540,-74.049638,40.724294,-74.035483,member
224403,E47ADF195554DD3E,classic_bike,2022-05-01 00:04:10,2022-05-01 00:18:44,JC Medical Center,JC011,Washington St,JC098,40.716540,-74.049638,40.724294,-74.035483,member
237836,F7AA5C52904F6DDF,electric_bike,2022-05-01 00:04:29,2022-05-01 00:08:05,8 St & Washington St,HB603,Adams St & 11 St,HB507,40.745984,-74.028199,40.750916,-74.033541,casual
268789,8DDD0552D490C5E3,classic_bike,2022-05-01 00:04:41,2022-05-01 00:08:06,Grove St PATH,JC005,JC Medical Center,JC011,40.719586,-74.043117,40.716540,-74.049638,member

In [7]:
#break out month
combined_citibike_csv['Trip Month'] = combined_citibike_csv["started_at"].dt.month_name()
combined_citibike_csv.head()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual,Trip Month
267840,E0888D1157FDBE22,classic_bike,2022-05-01 00:01:29,2022-05-01 00:06:52,Columbus Dr at Exchange Pl,JC106,Morris Canal,JC072,40.716870,-74.032810,40.712419,-74.038526,member,May
224784,BC0481A24404E4A6,electric_bike,2022-05-01 00:03:39,2022-05-01 00:18:45,JC Medical Center,JC011,Washington St,JC098,40.716540,-74.049638,40.724294,-74.035483,member,May
224403,E47ADF195554DD3E,classic_bike,2022-05-01 00:04:10,2022-05-01 00:18:44,JC Medical Center,JC011,Washington St,JC098,40.716540,-74.049638,40.724294,-74.035483,member,May
237836,F7AA5C52904F6DDF,electric_bike,2022-05-01 00:04:29,2022-05-01 00:08:05,8 St & Washington St,HB603,Adams St & 11 St,HB507,40.745984,-74.028199,40.750916,-74.033541,casual,May
268789,8DDD0552D490C5E3,classic_bike,2022-05-01 00:04:41,2022-05-01 00:08:06,Grove St PATH,JC005,JC Medical Center,JC011,40.719586,-74.043117,40.716540,-74.049638,member,May

In [9]:
combined_citibike_csv.value_counts("member_casual")

member_casual
member    318360
casual    193401
dtype: int64

In [10]:
combined_citibike_csv.value_counts("Trip Month")

Trip Month
August       115231
July         108502
September    104247
June         103299
May           80482
dtype: int64

In [11]:
# Export the DataFrame as a CSV file. 
combined_citibike_csv.to_csv("Resources/combined_citibike.csv", encoding='utf8', index=False)